const chatMessages = [
    { sender: 'Player 2', text: "Hey hi man!!" },
    { sender: 'Player 2', text: "How is everything going for u?" },
    { sender: 'Player 2', text: "Is that Bad time to talk?" },
    { sender: 'Player 1', text: "No man, Drinking cold drink " },
    { sender: 'Player 1', text: "I'm Good, How about you?" },
    { sender: 'Player 2', text: "I'm doing well... Would you like to play a game?" },
    { sender: 'Player 1', text: "I would love to, but my internet connection seems a bit slow at the moment." },
    { sender: 'Player 1', text: "Oh, never mind." },
    { sender: 'Player 1', text: "My connection is back now." },
    { sender: 'Player 2', text: "Excellent! Shall we begin?" },
    { sender: 'Player 1', text: "Actually, I've never played this before. Could you explain how it works?" },
    { sender: 'Player 2', text: "Of course, it's quite simple." },
    { sender: 'Player 2', text: "First, please log in, search for my username 'Jalaj', and send me an invitation." },
    { sender: 'Player 2', text: "Once you've done that, go ahead and send the invite." },
    { sender: 'Player 1', text: "I've already sent it a few times. Let me check the connection again." },
    { sender: 'Player 2', text: "One player is selected to draw a secret word." },
    { sender: 'Player 2', text: "The remaining players must guess the word by typing their answers in the chat." },
    { sender: 'Player 1', text: "I see, similar to Pictionary?" },
    { sender: 'Player 2', text: "Exactly. The only difference is that it's played digitally instead of on paper." },
    { sender: 'Player 2', text: "Points are awarded based on how quickly you guess correctly." },
    { sender: 'Player 2', text: "The person drawing also earns points whenever someone guesses correctly." },
    { sender: 'Player 1', text: "That's a fair system. Even the artist benefits." },
    { sender: 'Player 2', text: "Precisely. So even those who aren't skilled at drawing still have a chance to win." },
    { sender: 'Player 1', text: "That's reassuring to hear." },
    { sender: 'Player 2', text: "There's also a timer for each round, so try to guess as quickly as possible." },
    { sender: 'Player 1', text: "Understood. I'm ready whenever you are." },
    { sender: 'Player 2', text: "Great, let's begin." },
    { sender: 'Player 1', text: "Just so you know, I'm not particularly good at drawing straight lines." },
    { sender: 'Player 2', text: "That's perfectly fine, most players aren't either." },
    { sender: 'Player 1', text: "In my last game, I attempted to draw a car." },
    { sender: 'Player 2', text: "How did that go?" },
    { sender: 'Player 1', text: "Everyone guessed it was a shoebox." },
    { sender: 'Player 2', text: "That's quite amusing, but at least it was memorable." },
    { sender: 'Player 1', text: "My drawing skills leave much to be desired." },
    { sender: 'Player 2', text: "I wouldn't worry about it too much, it's all in good fun." },
    { sender: 'Player 1', text: "I tend to be better at guessing than drawing." },
    { sender: 'Player 2', text: "I feel the same way." },
    { sender: 'Player 1', text: "What's your preferred word to draw?" },
    { sender: 'Player 2', text: "Pizza. It's simply a triangle with a few dots for toppings." },
    { sender: 'Player 1', text: "That's a reasonable choice." },
    { sender: 'Player 2', text: "Is there a word you particularly dislike?" },
    { sender: 'Player 1', text: "Bicycle." },
    { sender: 'Player 2', text: "May I ask why?" },
    { sender: 'Player 1', text: "It involves too many circles for my liking." },
    { sender: 'Player 2', text: "That's understandable." },
    { sender: 'Player 1', text: "I hope I don't get assigned the word 'helicopter' today." },
    { sender: 'Player 2', text: "If you do, simply draw a fan with legs attached." },
    { sender: 'Player 1', text: "That's actually a clever suggestion." },
    { sender: 'Player 2', text: "Please try not to laugh too much at my drawings." },
    { sender: 'Player 1', text: "I can't make any promises." },
    { sender: 'Player 2', text: "At the very least, please make an effort to guess them." },
    { sender: 'Player 1', text: "Only if you do the same for mine." },
    { sender: 'Player 2', text: "Agreed, that sounds fair." },
    { sender: 'Player 1', text: "It appears more players are joining the game." },
    { sender: 'Player 2', text: "Wonderful, the game should be starting shortly." },
    { sender: 'Player 1', text: "Let's see how it goes. Best of luck to you." },
    { sender: 'Player 2', text: "Best of luck to you as well." }
];

export default chatMessages;